
services:
  #  Service MongoDB
  mongo_db:
    image: mongo:6.0
    container_name: mongo_db
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    volumes:
      - mongo_data:/data/db  # Volume persistant pour MongoDB

  #  Service de l'application Python
  healthcare_app:
    build:
      #  Adapter ce chemin selon le dossier o√π se trouve le projet
        context: .               
        dockerfile: docker/Dockerfile  
    container_name: healthcare_app
    depends_on:
      - mongo_db
    environment:
      MONGO_URI: ${MONGO_URI}
    # Montage du dossier app pour que les fichiers sortants soient visibles localement
    volumes:
      - ./app:/app/data
    command: ["python3", "app/main.py"]

#  Volumes persistants
volumes:
  mongo_data:
  csv_data:   
